### PR TITLE
feat(import-flow):fix git url validation issues

### PR DESCRIPTION
**Pull request by debsmita1**
- This PR contains the bug fixes for the issue raised in https://jira.coreos.com/browse/ODC-665
- Error message is displayed to the user when GitSourceAnalysis CR fails to detect a build image
- In case of an invalid git url , where the user enters special characters in `Git Repository URL` input field, a generic error message is displayed

Watch video here : https://youtu.be/EqJnEpppVic

### CODE REVIEW

**Comment by christianvogt** [comment]
Watching the video at 14secs, you manually enter a builder image. At which point the green checkmark appears. I do not agree that the checkmark should be here because wasn't that there to convey that a match was found? Furthermore once a value has been manually entered, detection shouldn't change the user's selection. It should only update if they haven't ever selected a value before. The item in the list should have a decoration indicating which one was detected. 

I know that some of what i describe will be covered when moving to the tile based chooser. And perhaps this PR is to focus only on fixing the errors in which case it seems to solve that.

**Comment by debsmita1** [comment]
@christianvogt  I have changed the implementation a bit. The green checkmark now appears only when builder image is auto detected. For user's manual selection, the checkmark wont show up. We can add the decorator when the tile based selector is in.

And what you said about the builder image detection shouldn't change user's manual selection, yes the `detectBuildTool` func sets the detected builder image only if the user has not selected any.
The question is, should we allow the user to select a build type after it is auto detected ? I am currently allowing this.

**Comment by christianvogt** [comment]
Yes let the user change the value after detection.

**Comment by debsmita1** [comment]
Then its already implemented in my code.

**Review by rohitkrai03 — APPROVED** [review]
LGTM

**Comment by christianvogt** [comment]
@debsmita1 If i go to the form and change the builder image, then start typing in the git url the builder image is deselected. This isn't part of the bugs you're fixing but you mentioned that the function doesn't update the builder image if the user manually set it. So although your statement is true, the form resets the user selection whenever the git url changes.

**Comment by debsmita1** [comment]
Yes the function doesnt update the builder image that is manually selected for the url entered at that moment. If the url is updated all the fields in the form is reset.

**Comment by christianvogt** [comment]
That's fine. It's not part of these issues and we can deal with it in another issue.

**Pull request merged**
