### PR TITLE
add owners and readme files to devconsole extension

### PR DESCRIPTION
**Pull request by christianvogt**
As per [Console Extensibility Plan](https://docs.google.com/document/d/1GtTvThPVn0PxPTbp2Hlpd7ABAjmW1Ul1uDsp77pk20E/), including an `OWNERS` file with team members as reviewers and approvers.

Also started a readme file for future additions.

### CODE REVIEW

**Review by rohitkrai03 — CHANGES_REQUESTED** [review]
@christianvogt I think both of these files should be under our component directory `frontend/public/extend/devconsole`.

**Comment by christianvogt** [comment]
Oops indeed. Bad copy from open pr on console repo :(

**Comment by joshuawilson** [comment]
@christianvogt are you going to move it to the last layer in the directory structure `devconsole`?

**Comment by christianvogt** [comment]
@rohitkrai03 @joshuawilson moved :P

**Review by rohitkrai03 — APPROVED** [review]
LGTM

**Pull request merged**
