### PR TITLE
fix(knative-icon): updates knative icon with white outline and position

### PR DESCRIPTION
**Pull request by invincibleJai**
- updates knative icon with white outline and position

Tracks: https://jira.coreos.com/browse/ODC-1028

Img : 

Screenshot 2019-06-06 at 12 53 25 PM

### CODE REVIEW

**Comment by christianvogt** [comment]
@invincibleJai did you update the icon to add that thin white line? We should be using filters to apply a white outline so that we do not have to modify the SVG.

**Comment by invincibleJai** [comment]
@christianvogt this is the final svg shared with UXD https://drive.google.com/drive/folders/1XgDL4K9q3O47suhJAkOFyz1Jep_Pn27- , have used the same in this PR and it already has white outline. Should we still use the filter as we got a white outline with icon

**Review by rohitkrai03 — APPROVED** [review]

**Review by joshuawilson — APPROVED** [review]

**Comment by christianvogt** [comment]
@serenamarie125 please comment
IMO that white outline is no where near large enough to distinguish the edge of the icon when it overlaps another icon at the default zoom level. Your description has the node at least 5x larger than the default and it is barely distinguishable here.

I say we need a larger outline as a white filter. Only question is whether it should be a hard line or a soft fade. Color should be white.

**Comment by christianvogt** [comment]
Note that since this is an official icon I'm ok if we address the outline in a separate PR and use this one to apply the new icon.

**Comment by invincibleJai** [comment]
@christianvogt yes in default zoom the outline of the icon is not visible. 

I'll have a subtask for clear outline and provide in other PR.

**Pull request merged**
