### PR TITLE
feat(codebase):Add codebase section to devops console

### PR DESCRIPTION
**Pull request by abhinandan13jan**
@rohitkrai03 @joshuawilson @christianvogt Adding a fresh PR to avoid conflict issues
CRD and resources are placed in extend/devconsole/components/__mocks__
run "oc create -f {relativepath}" to extend kubernetes API with CRD
run "oc create -f {relativepath} --namespace={namespace}" to add resources to the CRD from __mocks__/resource directory

### CODE REVIEW

**Comment by rohitkrai03** [comment]
@abhinandan13jan Can you add some screenshots or GIF to the PR description? I am reviewing your PR and testing it locally but i have no reference in terms what to expect from UI.

**Comment by abhinandan13jan** [comment]
@rohitkrai03 @joshuawilson @christianvogt @nimishamukherjee  Updated. For testing the PR, please extend the API with the mock CRD and resources. You can do the following by executing the oc command
"oc create -f {relativepath}" The CRD and resources are placed as yaml in extend/devconsole/components/  mocks

Once these are in place visit the devops/codebases route to view list of cobebases in the current namespace
Screenshot from 2019-03-17 14-45-37

Toggle between namespaces and all-namespace view by using the namespace bar on top left corner
Screenshot from 2019-03-17 14-45-14

Filter out the list and sort according to a column preference
Screenshot from 2019-03-17 14-45-25

Get details of a particular resource by clicking on it
Screenshot from 2019-03-17 14-45-45

Kindly review at the earliest. We have the sprint end nearing

**Comment by abhinandan13jan** [comment]
@rohitkrai03 @joshuawilson @christianvogt please review

**Comment by joshuawilson** [comment]
PM has decided that this view is not required. Therefore this PR is now obsolete.

**Pull request closed without merging**
